apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: pacman-1fyz
  namespace: showeimer-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:27e0acf98c541d2d8508d7e12f86d69f41e781dc13c72b1b9899d3bd8c6bde50
        name: container-image
        resources: {}
status: {}
