apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman-1fyz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman-1fyz
    app.kubernetes.io/part-of: sho-pacman2
  name: pacman-1fyz
  namespace: showeimer-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: pacman-1fyz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: pacman-1fyz
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:74f381bc7b9191aef603fc15857b2d7fb7caafcee83bbaa597e990a860c38396
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
