apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman-1fyz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman-1fyz
    app.kubernetes.io/part-of: sho-pacman2
  name: pacman-1fyz
  namespace: showeimer-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: pacman-1fyz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: pacman-1fyz
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:27e0acf98c541d2d8508d7e12f86d69f41e781dc13c72b1b9899d3bd8c6bde50
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 3001
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 3001
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
