apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman-1fyz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman-1fyz
    app.kubernetes.io/part-of: sho-pacman2
  name: pacman-1fyz
  namespace: showeimer-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: pacman-1fyz
status:
  loadBalancer: {}
